### ISSUE TITLE
exceeded maximum execution time

### ISSUE THREAD

**Issue by abby-thien-ai** [brokensandals/export-google-docs#1]
hi!

I've been using this code to backup a folder on my google drive for a while. Recently it began to fail and say that it exceeded the maximum execution time - is this because the folder has exceeded the max size or is there another reason?

thanks!

**Comment by brokensandals** [comment]
Hi! That error means the script is taking too long - there's a hard limit of 6 minutes I think (see https://developers.google.com/apps-script/guides/services/quotas). There isn't a direct limitation on the size of the folder, and if you were hitting the hard 10MB limit on file size the error would mention file size specifically. But the number and size of the files do affect how long the script takes.

Here are a few different ideas for things you could try to speed the script up:

- Remove the code that exports to PDF, if you don't use the PDFs (or remove the Office document exports if you only care about the PDFs)
- If you're using the version of the script that backs up all the data into a single zip file, try one of the branches that puts each input file into a separate zip file; or vice versa. I don't know which is faster.
- Don't zip the backup files at all, just save them to a folder

Or, you could try splitting the work across multiple executions of the script. Perhaps make one execution responsible for backing up files whose names start in the first half of the alphabet, and another execution responsible for other files, or something like that.

Or, you could use/write a similar export script that runs on your local machine (or on a server you control or a service like AWS Lambda), so that you wouldn't have an execution time limit. I think there are some out there - for example, https://github.com/vikynandha-zz/google-drive-backup came up on a github search - but I haven't tried any of them.

**Comment by abby-thien-ai** [comment]
The PDF thing fixed it! Thanks so much for your help :)
